[package]
name = "example-yew-use-state-counter"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-wasm-binding = { path = "../../../rust-wasm-binding", default-features = false }
yew = { path = "../../packages/yew", features = ["csr"] }

[features]
coverage = ["rust-wasm-binding/coverage"]
